export const SAVE_RECORD_REQUEST ='SAVE_RECORD_REQUEST';
export const SAVE_RECORD_SUCCESS = 'SAVE_RECORD_SUCCESS';
export const SAVE_RECORD_FAIL = 'SAVE_RECORD FAIL';

export const EDIT_RECORD_REQUEST = 'EDIT_RECORD_REQUEST';
export const EDIT_RECORD_SUCCESS = 'EDIT_RECORD_SUCCESS';
export const EDIT_RECORD_FAIL = 'EDIT_RECORD_FAIL';

export const DELETE_RECORD_REQUEST = 'DELETE_RECORD_REQUEST'
export const DELETE_RECORD_SUCCESS = 'DELETE_RECORD_SUCCESS'
export const DELETE_RECORD_FAIL = 'DELETE_RECORD_FAIL'